### ISSUE TITLE
项目在浏览器打开后，切换为手机模式，不能滚动,刷新后可以，请问这个是为什么？

### ISSUE THREAD

**Issue by wangtangsheng** [ustbhuangyi/vue-sell#34]
项目在浏览器打开后，切换为手机模式，不能滚动,刷新后可以，请问这个是为什么？

**Comment by boomkasl** [comment]
> sell@1.0.0 dev E:\vue-sell-master
> node build/dev-server.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\vue-sell-master\build\check-versions.js:1:76)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sell@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sell@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-08-06T16_54_05_365Z-debug.log
为什么我用 npm run dev 时出现上述的报错
用的是老师的源码没做任何修改
